### ISSUE TITLE
Puzzling build failure

### ISSUE THREAD

**Issue by jgm** [haskell-hvr/HsYAML#1]
I've switched to using HsYAML in pandoc, but my Travis build has a mysterious failure for ghc 8.4.1.
```
Building library for HsYAML-0.1.1.1..
[1 of 7] Compiling Util             ( src/Util.hs, dist/build/Util.o )
src/Util.hs:12:7: error: Not in scope: ‘liftEither’
   |
12 |     ( liftEither
   |       ^^^^^^^^^^
```
Other ghc versions work fine.  As far as I can see, HsYAML should work for both newer and older versions of mtl.  So I don't understand where this error could be coming from.  Any thoughts?

**Comment by jgm** [comment]
ah, that clears things up!  Thanks.

Herbert Valerio Riedel <notifications@github.com>
writes:

**Comment by hvr** [comment]
@jgm fyi, I just released http://hackage.haskell.org/package/HsYAML-0.1.1.2 which also works w/ GHC 8.4.1 bad mtl-2.2.2
