### ISSUE TITLE
Export getDoc

### ISSUE THREAD

**Issue by sjakobi** [haskell-hvr/HsYAML#32]
It's just slightly inconvenient to have to pattern match on `Doc`.

**Comment by sjakobi** [comment]
Seems like this was recently fixed on the `0.2` branch.

**Comment by sjakobi** [comment]
Would be nice to get a release though! :)

**Comment by hvr** [comment]
@sjakobi are you sure? afaics, `getDoc` is currently *not* exported in the 0.2 branch...

**Comment by sjakobi** [comment]
Ah, I think I got confused by the export from `Internal.hs`, where it is exported.

**Comment by hvr** [comment]
@sjakobi I'll add something for 0.2.1

but out of curiosity, what kind of code are you writing that the newtype becomes awkward to use?

**Comment by sjakobi** [comment]
> what kind of code are you writing that the newtype becomes awkward to use?

I was just exploring a bit in the REPL with `decodeNode`. I probably saw `getDoc` in the `show` output and wondered why I couldn't use it or so.

**Comment by sjakobi** [comment]
> I plan to release HsYAML-0.2.1 later today

Sounds great! :)

No specific wishes though. I haven't touched the YAML-handling it dhall yet.
