### ISSUE TITLE
Cannot install HsYAML on alpine linux 3.12

### ISSUE THREAD

**Issue by perlpunk** [haskell-hvr/HsYAML#51]
I'm trying to install HsYAML on alpine linux 3.12.0.
Dockerfile:
https://github.com/yaml/yaml-runtimes/blob/update-alpine/docker/haskell/alpine-builder.dockerfile
Install script:
https://github.com/yaml/yaml-runtimes/blob/update-alpine/docker/haskell/utils/hs-build.sh

Error message:
https://gist.github.com/perlpunk/86d8701d971bcb423b7d821954e4da52#file-build-hsyaml-log

Any idea what I could do?

See also https://github.com/yaml/yaml-runtimes/issues/8

**Comment by andreasabel** [comment]
This might be fixed by the latest revision on hackage.
https://hackage.haskell.org/package/HsYAML-0.2.1.0/revisions/
