### ISSUE TITLE
Bad #if breaks build on ghc-8.4.2

### ISSUE THREAD

**Issue by ddssff** [haskell-hvr/HsYAML#6]
This #if:

    #if !MIN_VERSION_mtl(2,2,2) || (__GLASGOW_HASKELL__ == 804 && __GLASGOW_HASKELL_PATCHLEVEL1__ < 2)

helps if you are on the very first release of ghc-8.4.1, but if you are on ghc-8.4.2 patchlevel 1 or ghc-8.4.3 patchlevel 1 it breaks the build.

**Comment by hvr** [comment]
I don't understand; the expression

    (__GLASGOW_HASKELL__ == 804 && __GLASGOW_HASKELL_PATCHLEVEL1__ < 2)

is supposed to denote the version range `ghc >= 8.4 && < 8.4.2`

note that "PATCHLEVEL1" is the 3rd component of the GHC version number; e.g. GHC 7.8.2.20140623 results in

```c
#define __GLASGOW_HASKELL__             708
#define __GLASGOW_HASKELL_PATCHLEVEL1__ 2
#define __GLASGOW_HASKELL_PATCHLEVEL2__ 20140623
```

**Comment by ddssff** [comment]
I will close.
