### ISSUE TITLE
Prelude.read Exception on valid YAML input

### ISSUE THREAD

**Issue by mb21** [haskell-hvr/HsYAML#7]
HsYAML fails ungracefully on:

    ---
    foo: 1e
    ---

In GHCI:

    :set +m

    import qualified Data.YAML as YAML
    import Data.ByteString.Char8

    case YAML.decodeStrict (pack "foo: 1e") of
      Right xs -> show xs
      Left err -> err

gives:

    "*** Exception: Prelude.read: no parse

Seems to come from https://github.com/haskell-hvr/HsYAML/blob/0.2/src/Data/YAML/Schema.hs#L321

We need this for https://github.com/jgm/pandoc/issues/5177

Thanks!

**Comment by jgm** [comment]
Line 313 should be `P.many1 digit`, not `P.many digit`.
The regex for floats in the YAML spec for "JSON Schema" is
```
-? ( 0 \| [1-9] [0-9]* ) ( \. [0-9]* )? ( [eE] [-+]? [0-9]+ )?
```

**Comment by jgm** [comment]
Many thanks!

**Comment by hvr** [comment]
@jgm @mb21 oh btw, I noticed you seem to assume that `decodeStrict` uses the JSON schema -- it doesn't! The docs for it say

> Decode YAML document(s) using the YAML 1.2 **Core schema**

And the bug you noticed applied to both, JSON & Core schema (c.f. 
cf78049)

**Comment by hvr** [comment]
> Oh, looking at the YAML docs, I had the impression
that automatic recognition of floats isn't done in the
core schema. Is that wrong?



Well, there's 3 Schemas, where failsafe is the most minimal/barebones one, the Json schema corresponds more or less to the JSON grammar, while the "Core" schema recognises more tokens than the JSON Schema:

- failsafe -- no auto-recognition of sclars at all
- JSON -- see regexps at https://yaml.org/spec/1.2/spec.html#id2804356
- Core -- (I just realised that I errornously call this "Core JSON" in the Haddocks -- it's called only "Core Schema"), see regexps at  https://yaml.org/spec/1.2/spec.html#id2805071

**Comment by jgm** [comment]
Ah, sorry, I just had the wrong terminology.
We went to using failsafe, which works well for our purposes.

Herbert Valerio Riedel <notifications@github.com>
writes:

>> Oh, looking at the YAML docs, I had the impression
> that automatic recognition of floats isn't done in the
> core schema. Is that wrong?
>
>
>
> Well, there's 3 Schemas, where failsafe is the most minimal/barebones one, the Json schema corresponds more or less to the JSON grammar, while the "Core" schema recognises more tokens than the JSON Schema:
